version: "3"

services:
  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_api_development

    ports:
      - '5432:5432'
    volumes:
      -   var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
      - '9292:9292'
    env_file:
      - .env.development
    command: rackup /web/config.ru
